# Generated by Django 4.2.8 on 2024-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('event_type', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
