# Generated by Django 4.2.8 on 2024-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
